// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZZRPIqu858B1fC1yTGBOJ3JsmW6m4I20',
    appId: '1:860655042376:web:6f0e877827580234527d7d',
    messagingSenderId: '860655042376',
    projectId: 'kasumbasawelas',
    authDomain: 'kasumbasawelas.firebaseapp.com',
    storageBucket: 'kasumbasawelas.firebasestorage.app',
    measurementId: 'G-HC5K0SR5Z3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFBT7COKKYFJHeKx911ImNzv-WJImmg28',
    appId: '1:860655042376:android:5806c5afd328f934527d7d',
    messagingSenderId: '860655042376',
    projectId: 'kasumbasawelas',
    storageBucket: 'kasumbasawelas.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7EvF3ssZkeLl8WcMXXquWmvI5nFxYGPU',
    appId: '1:860655042376:ios:527b7805059600ed527d7d',
    messagingSenderId: '860655042376',
    projectId: 'kasumbasawelas',
    storageBucket: 'kasumbasawelas.firebasestorage.app',
    iosBundleId: 'com.example.kasumbasawelas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7EvF3ssZkeLl8WcMXXquWmvI5nFxYGPU',
    appId: '1:860655042376:ios:527b7805059600ed527d7d',
    messagingSenderId: '860655042376',
    projectId: 'kasumbasawelas',
    storageBucket: 'kasumbasawelas.firebasestorage.app',
    iosBundleId: 'com.example.kasumbasawelas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZZRPIqu858B1fC1yTGBOJ3JsmW6m4I20',
    appId: '1:860655042376:web:82ce821bafae87e0527d7d',
    messagingSenderId: '860655042376',
    projectId: 'kasumbasawelas',
    authDomain: 'kasumbasawelas.firebaseapp.com',
    storageBucket: 'kasumbasawelas.firebasestorage.app',
    measurementId: 'G-27S26GGZ5K',
  );
}
